-- 이전 버전 문법 사용 가능하게 해줌
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- todo 유저 생성
CREATE USER todo IDENTIFIED BY todo;

-- todo 유저 권한 설정
GRANT CONNECT, RESOURCE TO todo;

-- DEFAULT TABLESPACE 설정
ALTER USER todo DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;