CREATE SEQUENCE SEQ_MEMBER_CODE
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_TODO_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- 회원 정보를 관리하는 테이블
CREATE TABLE TB_MEMBER (
	MEMBER_CODE NUMBER CONSTRAINT MEM_CODE_PK PRIMARY KEY,
	MEMBER_ID 	NVARCHAR2(10) CONSTRAINT MEM_ID_NN NOT NULL,
	MEMBER_PW 	NVARCHAR2(20) CONSTRAINT MEM_PW_NN NOT NULL,
	NICKNAME 		VARCHAR2(15) CONSTRAINT NICK_UNQ UNIQUE,
	CONSTRAINT MEM_ID_UNQ UNIQUE(MEMBER_ID)
);

COMMENT ON COLUMN TB_MEMBER.MEMBER_CODE IS '회원식별코드';
COMMENT ON COLUMN TB_MEMBER.MEMBER_ID 	IS '회원아이디';
COMMENT ON COLUMN TB_MEMBER.MEMBER_PW 	IS '회원비밀번호';
COMMENT ON COLUMN TB_MEMBER.NICKNAME 		IS '닉네임';

-- ToDoList를 관리하는 테이블
CREATE TABLE TB_TODO (
	MEMBER_CODE		NUMBER CONSTRAINT MEM_CODE_FK REFERENCES TB_MEMBER ON DELETE CASCADE,
	TODO_NO 			NUMBER CONSTRAINT TODO_NO_PK PRIMARY KEY,
	TODO_TITLE 		NVARCHAR2(30) DEFAULT '제목',
	HAS_DONE 			CHAR(1) DEFAULT 'N' CONSTRAINT HAS_DONE_NN NOT NULL,
	CREATED_DATE 	DATE DEFAULT CURRENT_DATE CONSTRAINT CREATED_DATE_NN NOT NULL,
	CONSTRAINT HAS_DONE_YN CHECK(HAS_DONE = 'Y' OR HAS_DONE = 'N')
);

COMMENT ON COLUMN TB_TODO.MEMBER_CODE 	IS '회원식별코드';
COMMENT ON COLUMN TB_TODO.TODO_NO 			IS 'todo번호';
COMMENT ON COLUMN TB_TODO.TODO_TITLE 		IS 'todo제목';
COMMENT ON COLUMN TB_TODO.HAS_DONE 			IS '완료여부';
COMMENT ON COLUMN TB_TODO.CREATED_DATE 	IS '생성날짜';